name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - LICENSE
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - LICENSE
      - 'README.md'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: Node ${{ matrix.node }} tests
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          check-latest: true
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v4

      - name: Install deps
        run: pnpm i

      - name: Run tests
        run: pnpm test
